name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Check formatting
        run: npm run format:check

      - name: Build project
        run: npm run build

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run tests (in PR's skip visual)
        if: github.event_name == 'pull_request'
        run: npm run test -- --grep-invert "Visual Regression" || true

      - name: Run tests (in push - include visual)
        if: github.event_name == 'push'
        run: npm run test || true

      - name: Update snapshots
        if: failure()
        run: |
          npx playwright install --with-deps
          npx playwright test --update-snapshots

      - name: Commit snapshots
        if: failure()
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git add tests/visual.spec.ts-snapshots/
          git diff --quiet tests/visual.spec.ts-snapshots/ || git commit -m "Update visual regression tests snapshots"
          git push origin HEAD:${{ github.ref_name }}
